language: node_js
before_script:
  - npm install -g roots
script:
  - npm test
  - roots compile -e production
node_js:
  - "0.12"

notifications:
  email:
    recipients:
      - aegaas@deloitte.com
      - aargyle@deloitte.com
