language: node_js
before_script:
- npm install -g roots
- npm install -g bower
script:
- npm test
- bower install
- roots compile -e staging
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
  - bower_components
notifications:
  email:
    recipients:
    - aegaas@deloitte.com
    - aargyle@deloitte.com
addons:
  ssh_known_hosts:
  - androidhub-int.wdg.infra-host.com
  - androidhub-prod.wdg.wdg.infra-host.com
deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: scripts/deploy_production.sh
    skip_cleanup: true
    on:
      tags: true
